baseURL = 'https://georgepool.com/'
languageCode = 'en-uk'
title = 'George Pool'
theme = 'PaperMod'

[deployment]

[[deployment.targets]]
name = "production"
URL = "gs://georgepool.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blogs/"
    weight = 2