baseURL = 'https://georgepool.github.io/portfolio-website/'
languageCode = 'en-uk'
title = 'George Pool'
theme = 'PaperMod'

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/georgepool"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blogs/"
    weight = 2

  [[menu.main]]
    identifier = "project"
    name = "Part II Project"
    url = "/part-ii-project/"
    weight = 3